version: '3'

services:
    brevetsapp:
        build: brevetsapp/
        command: python -u flask_brevets.py
        ports:
            - "5000:5000"
        depends_on:
            - brevet
        environment:
            MONGODB_HOSTNAME: brevet
    restapi:
        build: api/
        command: python -u api.py
        depends_on:
            - brevet
        environment:
            MONGODB_HOSTNAME: brevet
    website:
        build: website/
        command: python -u website.py
        ports:
            - "6002:5000"
        depends_on:
            - restapi
    brevet:
        image: mongo:latest